### ISSUE TITLE
Webdriver can't connect to server

### ISSUE THREAD

**Issue by yweiner** [groupon/webdriver-http-sync#43]
I have set up my file according to the documentation:

```
var WebDriver = require('webdriver-http-sync');
var desiredCapabilities = {browserName: 'firefox'};
var driver = new WebDriver('http://127.0.0.1:4444/wd/hub', desiredCapabilities);
```

and then I instantiate `driver.navigateTo('https://www.google.com');`

when i run the file from terminal 'node selenium-test-http-sync.js' it gives me the following error and then breaks:

`Failed to start WebDriver session: Couldn't connect to server`

Why is this happening?

**Comment by EndangeredMassa** [comment]
Closing due to age. If this is an issue again, please open a new issue.
